language: node_js
node_js:
  - "4"
  - "7"
  - "8"
  - "9"

os:
  - linux
  - osx

sudo: required

cache:
  directories:
    - node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install shellcheck; fi
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

script:
  - echo $TRAVIS_OS_NAME
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - node --version
  - npm --version
  - ./admin/test.sh

after_success:
  - npm run coverage

stages:
  - test
  - pack
  - name: deploy
    if: branch =~ ^(master|v\d+\.\d+)
